var myDate = new Date();
console.log(myDate.toTimeString())
console.log(myDate.toLocaleTimeString())
console.log(myDate.toLocaleDateString())
console.log(myDate.getMonth())
console.log(myDate.getDate())
console.log(myDate.getMilliseconds())
console.log(myDate.getHours())
console.log(myDate.getDay())
console.log(myDate.getTimezoneOffset())